[General]
DisplayServer=wayland

[Theme]
Current=zelix-aurora
CursorTheme=breeze_cursors

[Autologin]
User=zelix
Session=plasma
Relogin=false

[Users]
MaximumUid=60000
MinimumUid=1000
RememberLastUser=true
